DATANAME = 'SZTAXI'
TIMESTEP_IN = 12
TIMESTEP_OUT = 12
N_NODE = 492
CHANNEL = 1
BATCHSIZE = 32
LEARN = 0.001
EPOCH = 200
PATIENCE = 10
OPTIMIZER = 'Adam'
# OPTIMIZER = 'RMSprop'
LOSS = 'MSE'
# LOSS = 'MAE'
TRAINRATIO = 0.8 # TRAIN + VAL
TRAINVALSPLIT = 0.125 # val_ratio = 0.8 * 0.125 = 0.1
FLOWPATH = '../SZTAXI/SZTAXI-speed.pkl'
ADJPATH = '../SZTAXI/adj_10.npy'
ADJTYPE = 'doubletransition'
